name       : haskell-x509-store
version    : 1.6.7
release    : 3
source     :
    - https://hackage.haskell.org/package/x509-store-1.6.7/x509-store-1.6.7.tar.gz : 9786356c8bfdf631ea018c3244d0854c6db2cb24e583891ea553961443f61ef9
license    : BSD-3-Clause
component  : programming.haskell
summary    : X.509 collection accessing and storing methods for certificate, crl, exception list
description: "X.509 collection accessing and storing methods for certificate, crl, exception list \n"
builddeps  :
    - haskell-cabal-install
    - haskell-x509-devel
rundeps    :
    - devel:
        - haskell-x509-devel
networking : yes
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
