name       : haskell-x509-store
version    : 1.6.2
release    : 1
source     :
    - http://hackage.haskell.org/package/x509-store-1.6.2/x509-store-1.6.2.tar.gz : 49fd261c7e55a45fd357931a6d9f81e22f242e6047304d3e2662e43db94d807b
license    : BSD-3-Clause
component  : programming.haskell
summary    : X.509 collection accessing and storing methods for certificate, crl, exception list 
description: |
    X.509 collection accessing and storing methods for certificate, crl, exception list 
builddeps  :
    - haskell-cabal-install
    - haskell-x509
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
