name       : haskell-x509-store
version    : 1.6.6
release    : 2
source     :
    - https://hackage.haskell.org/package/x509-store-1.6.6/x509-store-1.6.6.tar.gz : 6a276f595cf91c9688129cad4c9c6be9c349ffc0de22300eeb3dfa6a2b6e7635
license    : BSD-3-Clause
component  : programming.haskell
summary    : X.509 collection accessing and storing methods for certificate, crl, exception list
description: "X.509 collection accessing and storing methods for certificate, crl, exception list \n"
builddeps  :
    - haskell-cabal-install
    - haskell-x509
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
